language: csharp
dotnet: 6.0
os: linux
dist: xenial
mono: none
sudo: required

install:
before_script:
script:
- dotnet build -c Release
- dotnet test test/Bitstamp.Client.Websocket.Tests -c Release
deploy:
  provider: script
  skip_cleanup: true
  script:
    - cd src/Bitstamp.Client.Websocket && dotnet pack /p:PackageVersion=1.0.$TRAVIS_BUILD_NUMBER -c Release && cd bin/Release && dotnet nuget push **/*.1.0.$TRAVIS_BUILD_NUMBER.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
  on:
    branch: master